version: '3'

services:

  gateway:
    build: ./services/gateway
    ports:
      - "80:80"
    volumes:
      - ./services/gateway/conf.d:/etc/nginx/conf.d/:cached

  mapsrv:
    image: ${REGISTRY}/mapsrv
    build: ./services/mapsrv
    environment:
      # Some envs are loaded from .env file in the project root
      FLASK_APP: mapsrv/main.py
      FLASK_ENV: development
      AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
      AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
    entrypoint: flask run --host=0.0.0.0
    volumes:
      - ./services/mapsrv:/usr/src/app:cached

  map:
    image: ${REGISTRY}/map
    build: ./services/map
    volumes:
      - ./services/map:/usr/share/nginx/html:cached

